travis:
  secure:
    BINSTAR_TOKEN: bVnHQ0XZMO5vsvSiuF7lYokz0XjkMlyFccw6ffhfU5Ka35tpOilALlhEUKAzz/W6YsWOK7HoUgrZY1WbKBuKrl45DJsNSKx1aDMX6fFwfyTHOZ8QDC5gtuC/AeQGVQLc4By4Sy8r8wRVmCD603Bg+AiMGxumy0181BIgw5Oy4bhhcTJ8fd08+n8aKbK1Gh6uac7DIPElIlNJ8slle3t9wsjsWFQfWGvjcSfEih0s7+FfG+IgeS2LEXRTyMJ1ZeTRBOiGpSc6Oq0CvvAQZwLeRshQ5ZWE+lJq4cAfOUkySi4707gIOqfPoFKpJzzYMdSP94hoSxifYMMMppW09GlPjP+GkfIbE14wPLkA7kBAJjVcw5vPwP7Rlfr5+gojXqZdtP6qT6GiSuHBmC4lszETT4OM3pXke4dJQjifX9r7bKI5OVU/smRfLVhfYxT3VNlKUBW52ZOegfRRbAL8AZjMtKccQPXM5X3X0HuzxJrlPpNzpGfy8dvPiJgMcJlhUGOZNUiV3Qgzl/ExSL093CxQO9iZ0xWs5UwoQ/rKGvJe1tj/11zPbmZZN3aPRfwC6TVikYTtdFtlUJajkiTVY6vyXZHDz3rMh90opXBEGXFMUy4kVr7rAfUqauVu/K3uXZ5Gvd2cWVo8QTvCXB2tz5bJQ3YowJNCs/K1xTzo9BZlNxQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
